### ISSUE TITLE
Can this plugin sort the footnote numbers automatically?

### ISSUE THREAD

**Issue by Triple-Z** [houkanshan/vscode-markdown-footnote#4]
For example:
```markdown
a[^2], b[^1]
[^1]: this is b.
[^2]: this is a.
```

Sorted by reading order:
```markdown
a[^1], b[^2]
[^1]: this is a.
[^2]: this is b.
```

**Comment by houkanshan** [comment]
No, it can't. It'll be a little tricky to implement this because identifiers in footnote references is not limited to number. 
e.g. `[^2] and [^bignote] and [^1]`
